// <auto-generated />
using System;
using System.Collections.Generic;
using Erc.Households.Domain.Billing;
using Erc.Households.EF.PostgreSQL;
using Erc.Households.ModelLogs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Erc.Households.EF.PostgreSQL.Migrations
{
    [DbContext(typeof(ErcContext))]
    [Migration("20200820080614_Add_Balance_History")]
    partial class Add_Balance_History
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:citext", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Erc.Households.Domain.AccountingPoints.AccountingPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'10000000', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AddressId")
                        .HasColumnName("address_id")
                        .HasColumnType("integer");

                    b.Property<int>("BranchOfficeId")
                        .HasColumnName("branch_office_id")
                        .HasColumnType("integer");

                    b.Property<int>("BuildingTypeId")
                        .HasColumnName("building_type_id")
                        .HasColumnType("integer");

                    b.Property<bool>("ContractIsSigned")
                        .HasColumnName("contract_is_signed")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Debt")
                        .HasColumnName("debt")
                        .HasColumnType("numeric");

                    b.Property<int>("DistributionSystemOperatorId")
                        .HasColumnName("distribution_system_operator_id")
                        .HasColumnType("integer");

                    b.Property<string>("Eic")
                        .IsRequired()
                        .HasColumnName("eic")
                        .HasColumnType("citext")
                        .HasMaxLength(16);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("citext")
                        .HasMaxLength(16);

                    b.Property<int>("OwnerId")
                        .HasColumnName("owner_id")
                        .HasColumnType("integer");

                    b.Property<int>("UsageCategoryId")
                        .HasColumnName("usage_category_id")
                        .HasColumnType("integer");

                    b.Property<int>("ZoneRecord")
                        .HasColumnName("zone_record")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_accounting_points");

                    b.HasIndex("AddressId")
                        .HasName("ix_accounting_points_address_id");

                    b.HasIndex("BranchOfficeId")
                        .HasName("ix_accounting_points_branch_office_id");

                    b.HasIndex("BuildingTypeId")
                        .HasName("ix_accounting_points_building_type_id");

                    b.HasIndex("DistributionSystemOperatorId")
                        .HasName("ix_accounting_points_distribution_system_operator_id");

                    b.HasIndex("Eic")
                        .IsUnique()
                        .HasName("ix_accounting_points_eic");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("ix_accounting_points_name");

                    b.HasIndex("OwnerId")
                        .HasName("ix_accounting_points_owner_id");

                    b.HasIndex("UsageCategoryId")
                        .HasName("ix_accounting_points_usage_category_id");

                    b.ToTable("accounting_points");

                    b.HasCheckConstraint("CK_accounting_point_eic", "length(eic) = 16");
                });

            modelBuilder.Entity("Erc.Households.Domain.AccountingPoints.BuildingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("HeataingCorrection")
                        .HasColumnName("heataing_correction")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_building_types");

                    b.ToTable("building_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HeataingCorrection = 1.0940m,
                            Name = "1-2 поверхи"
                        },
                        new
                        {
                            Id = 3,
                            HeataingCorrection = 0.7980m,
                            Name = "3 поверхи і більше"
                        });
                });

            modelBuilder.Entity("Erc.Households.Domain.AccountingPoints.UsageCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<IEnumerable<ExemptionDiscountNorms>>("ExemptionDiscountNorms")
                        .HasColumnName("exemption_discount_norms")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_usage_categories");

                    b.ToTable("usage_categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Звичайне споживання"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Електроплита"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Електроопалювальна установка"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Електроопалювальна установка та електроплита"
                        });
                });

            modelBuilder.Entity("Erc.Households.Domain.Addresses.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Apt")
                        .HasColumnName("apt")
                        .HasColumnType("citext")
                        .HasMaxLength(5);

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnName("building")
                        .HasColumnType("citext")
                        .HasMaxLength(10);

                    b.Property<int>("StreetId")
                        .HasColumnName("street_id")
                        .HasColumnType("integer");

                    b.Property<string>("Zip")
                        .HasColumnName("zip")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.HasIndex("StreetId")
                        .HasName("ix_addresses_street_id");

                    b.ToTable("addresses");

                    b.HasCheckConstraint("ck_address_zip", "zip ~ '^(\\d){5}$'");
                });

            modelBuilder.Entity("Erc.Households.Domain.Addresses.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DistrictId")
                        .HasColumnName("district_id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDistrictCity")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_district_city")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRegionCity")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_region_city")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("citext")
                        .HasMaxLength(100);

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex("DistrictId")
                        .HasName("ix_cities_district_id");

                    b.ToTable("cities");
                });

            modelBuilder.Entity("Erc.Households.Domain.Addresses.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("citext")
                        .HasMaxLength(100);

                    b.Property<int>("RegionId")
                        .HasColumnName("region_id")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_districts");

                    b.HasIndex("RegionId")
                        .HasName("ix_districts_region_id");

                    b.ToTable("districts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Андрушівський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Баранiвський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Бердичiвський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Брусилівський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Хорошівський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ємільчинський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Житомирський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Коростенський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Коростишiвський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Лугинський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Любарський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Малинський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Народицький район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "Новоград-Волинський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 15,
                            Name = "Овруцький район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 16,
                            Name = "Олевський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 17,
                            Name = "Попільнянський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 18,
                            Name = "Радомишльський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 19,
                            Name = "Романівський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 20,
                            Name = "Ружинський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 21,
                            Name = "Пулинський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 22,
                            Name = "Черняхівський район",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 23,
                            Name = "Чуднівський район",
                            RegionId = 1
                        });
                });

            modelBuilder.Entity("Erc.Households.Domain.Addresses.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("citext")
                        .HasMaxLength(100);

                    b.HasKey("Id")
                        .HasName("pk_regions");

                    b.ToTable("regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Житомирська обл."
                        });
                });

            modelBuilder.Entity("Erc.Households.Domain.Addresses.Street", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CityId")
                        .HasColumnName("city_id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("citext")
                        .HasMaxLength(100);

                    b.HasKey("Id")
                        .HasName("pk_streets");

                    b.HasIndex("CityId")
                        .HasName("ix_streets_city_id");

                    b.ToTable("streets");
                });

            modelBuilder.Entity("Erc.Households.Domain.Billing.AccountingPointDebtHistory", b =>
                {
                    b.Property<int>("AccountingPointId")
                        .HasColumnName("accounting_point_id")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodId")
                        .HasColumnName("period_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("DebtValue")
                        .HasColumnName("debt_value")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("AccountingPointId", "PeriodId")
                        .HasName("pk_accounting_point_debt_history");

                    b.ToTable("accounting_point_debt_history");
                });

            modelBuilder.Entity("Erc.Households.Domain.Billing.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AccountingPointId")
                        .HasColumnName("accounting_point_id")
                        .HasColumnType("integer");

                    b.Property<string>("CounterSerialNumber")
                        .HasColumnName("counter_serial_number")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnName("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DsoConsumptionId")
                        .HasColumnName("dso_consumption_id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ExemptionCoeff")
                        .HasColumnName("exemption_coeff")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("FromDate")
                        .HasColumnName("from_date")
                        .HasColumnType("date");

                    b.Property<decimal>("IncomingBalance")
                        .HasColumnName("incoming_balance")
                        .HasColumnType("numeric");

                    b.Property<string>("Note")
                        .HasColumnName("note")
                        .HasColumnType("text");

                    b.Property<int>("PeriodId")
                        .HasColumnName("period_id")
                        .HasColumnType("integer");

                    b.Property<int>("TariffId")
                        .HasColumnName("tariff_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ToDate")
                        .HasColumnName("to_date")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalAmountDue")
                        .HasColumnName("total_amount_due")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalCharge")
                        .HasColumnName("total_charge")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnName("total_discount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TotalUnits")
                        .HasColumnName("total_units")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnName("type")
                        .HasColumnType("integer");

                    b.Property<Usage>("UsageT1")
                        .HasColumnName("usage_t1")
                        .HasColumnType("jsonb");

                    b.Property<Usage>("UsageT2")
                        .HasColumnName("usage_t2")
                        .HasColumnType("jsonb");

                    b.Property<Usage>("UsageT3")
                        .HasColumnName("usage_t3")
                        .HasColumnType("jsonb");

                    b.Property<int>("ZoneRecord")
                        .HasColumnName("zone_record")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("AccountingPointId")
                        .HasName("ix_invoices_accounting_point_id");

                    b.HasIndex("DsoConsumptionId")
                        .IsUnique()
                        .HasName("ix_invoices_dso_consumption_id");

                    b.HasIndex("PeriodId")
                        .HasName("ix_invoices_period_id");

                    b.HasIndex("TariffId")
                        .HasName("ix_invoices_tariff_id");

                    b.ToTable("invoices");
                });

            modelBuilder.Entity("Erc.Households.Domain.Billing.InvoicePaymentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnName("amount")
                        .HasColumnType("numeric");

                    b.Property<int>("InvoiceId")
                        .HasColumnName("invoice_id")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentId")
                        .HasColumnName("payment_id")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_invoice_payment_item");

                    b.HasIndex("InvoiceId")
                        .HasName("ix_invoice_payment_item_invoice_id");

                    b.HasIndex("PaymentId")
                        .HasName("ix_invoice_payment_item_payment_id");

                    b.ToTable("invoice_payment_item");
                });

            modelBuilder.Entity("Erc.Households.Domain.Billing.Period", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnName("end_date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("citext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("start_date")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("pk_period");

                    b.HasIndex("StartDate")
                        .IsUnique()
                        .HasName("ix_periods_start_date");

                    b.ToTable("periods");

                    b.HasData(
                        new
                        {
                            Id = 201901,
                            EndDate = new DateTime(2019, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Січень 2019р.",
                            StartDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 201902,
                            EndDate = new DateTime(2019, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Лютий 2019р.",
                            StartDate = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 201903,
                            EndDate = new DateTime(2019, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Березень 2019р.",
                            StartDate = new DateTime(2019, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 201904,
                            EndDate = new DateTime(2019, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Квітень 2019р.",
                            StartDate = new DateTime(2019, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 201905,
                            EndDate = new DateTime(2019, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Травень 2019р.",
                            StartDate = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 201906,
                            EndDate = new DateTime(2019, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Червень 2019р.",
                            StartDate = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 201907,
                            EndDate = new DateTime(2019, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Липень 2019р.",
                            StartDate = new DateTime(2019, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 201908,
                            EndDate = new DateTime(2019, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Серпень 2019р.",
                            StartDate = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 201909,
                            EndDate = new DateTime(2019, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Вересень 2019р.",
                            StartDate = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 201910,
                            EndDate = new DateTime(2019, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Жовтень 2019р.",
                            StartDate = new DateTime(2019, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 201911,
                            EndDate = new DateTime(2019, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Листопад 2019р.",
                            StartDate = new DateTime(2019, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 201912,
                            EndDate = new DateTime(2019, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Грудень 2019р.",
                            StartDate = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 202001,
                            EndDate = new DateTime(2019, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Січень 2020р.",
                            StartDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 202002,
                            EndDate = new DateTime(2019, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Лютий 2020р.",
                            StartDate = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 202003,
                            EndDate = new DateTime(2019, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Березень 2020р.",
                            StartDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 202004,
                            EndDate = new DateTime(2019, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Квітень 2020р.",
                            StartDate = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 202005,
                            EndDate = new DateTime(2019, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Травень 2020р.",
                            StartDate = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 202006,
                            EndDate = new DateTime(2019, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Червень 2020р.",
                            StartDate = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 202007,
                            EndDate = new DateTime(2019, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Липень 2020р.",
                            StartDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Erc.Households.Domain.Billing.ZoneCoeff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("DiscountWeight")
                        .HasColumnName("discount_weight")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("start_date")
                        .HasColumnType("date");

                    b.Property<decimal>("Value")
                        .HasColumnName("value")
                        .HasColumnType("numeric");

                    b.Property<int>("ZoneNumber")
                        .HasColumnName("zone_number")
                        .HasColumnType("integer");

                    b.Property<int>("ZoneRecord")
                        .HasColumnName("zone_record")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_zone_coeffs");

                    b.ToTable("zone_coeffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscountWeight = 1m,
                            StartDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1m,
                            ZoneNumber = 1,
                            ZoneRecord = 1
                        },
                        new
                        {
                            Id = 2,
                            DiscountWeight = 0.67m,
                            StartDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.5m,
                            ZoneNumber = 1,
                            ZoneRecord = 2
                        },
                        new
                        {
                            Id = 3,
                            DiscountWeight = 0.33m,
                            StartDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1m,
                            ZoneNumber = 2,
                            ZoneRecord = 2
                        },
                        new
                        {
                            Id = 4,
                            DiscountWeight = 0.46m,
                            StartDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.4m,
                            ZoneNumber = 1,
                            ZoneRecord = 3
                        },
                        new
                        {
                            Id = 5,
                            DiscountWeight = 0.33m,
                            StartDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1m,
                            ZoneNumber = 2,
                            ZoneRecord = 3
                        },
                        new
                        {
                            Id = 6,
                            DiscountWeight = 0.21m,
                            StartDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1.5m,
                            ZoneNumber = 3,
                            ZoneRecord = 3
                        });
                });

            modelBuilder.Entity("Erc.Households.Domain.BranchOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("address")
                        .HasColumnType("citext")
                        .HasMaxLength(500);

                    b.Property<int>("CurrentPeriodId")
                        .HasColumnName("current_period_id")
                        .HasColumnType("integer");

                    b.Property<int[]>("DistrictIds")
                        .HasColumnName("district_ids")
                        .HasColumnType("integer[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("citext")
                        .HasMaxLength(200);

                    b.Property<string>("StringId")
                        .IsRequired()
                        .HasColumnName("string_id")
                        .HasColumnType("citext")
                        .HasMaxLength(2);

                    b.HasKey("Id")
                        .HasName("pk_branch_offices");

                    b.HasIndex("CurrentPeriodId")
                        .HasName("ix_branch_offices_current_period_id");

                    b.ToTable("branch_offices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 1 },
                            Name = "Андрушівський ЦОК",
                            StringId = "an"
                        },
                        new
                        {
                            Id = 2,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 2 },
                            Name = "Баранiвський ЦОК",
                            StringId = "bn"
                        },
                        new
                        {
                            Id = 3,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 3 },
                            Name = "Бердичiвський ЦОК",
                            StringId = "bd"
                        },
                        new
                        {
                            Id = 4,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 4 },
                            Name = "Брусилівський ЦОК",
                            StringId = "br"
                        },
                        new
                        {
                            Id = 5,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 5 },
                            Name = "Хорошівський ЦОК",
                            StringId = "hr"
                        },
                        new
                        {
                            Id = 6,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 6 },
                            Name = "Ємільчинський ЦОК",
                            StringId = "em"
                        },
                        new
                        {
                            Id = 7,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 7 },
                            Name = "Житомирський ЦОК",
                            StringId = "zt"
                        },
                        new
                        {
                            Id = 8,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 7 },
                            Name = "Зарічанський ЦОК",
                            StringId = "zr"
                        },
                        new
                        {
                            Id = 9,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 8, 10 },
                            Name = "Коростенський ЦОК",
                            StringId = "kr"
                        },
                        new
                        {
                            Id = 10,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 9 },
                            Name = "Коростишiвський ЦОК",
                            StringId = "kt"
                        },
                        new
                        {
                            Id = 11,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 11 },
                            Name = "Любарський ЦОК",
                            StringId = "lb"
                        },
                        new
                        {
                            Id = 12,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 12 },
                            Name = "Малинський ЦОК",
                            StringId = "ml"
                        },
                        new
                        {
                            Id = 13,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 13 },
                            Name = "Народицький ЦОК",
                            StringId = "nr"
                        },
                        new
                        {
                            Id = 14,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 14 },
                            Name = "Новоград-Волинський ЦОК",
                            StringId = "nv"
                        },
                        new
                        {
                            Id = 15,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 15 },
                            Name = "Овруцький ЦОК",
                            StringId = "ov"
                        },
                        new
                        {
                            Id = 16,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 16 },
                            Name = "Олевський ЦОК",
                            StringId = "ol"
                        },
                        new
                        {
                            Id = 17,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 17, 20 },
                            Name = "Попільнянський ЦОК",
                            StringId = "pp"
                        },
                        new
                        {
                            Id = 18,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 18 },
                            Name = "Радомишльський ЦОК",
                            StringId = "rd"
                        },
                        new
                        {
                            Id = 19,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 19 },
                            Name = "Романівський ЦОК",
                            StringId = "rm"
                        },
                        new
                        {
                            Id = 20,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 21 },
                            Name = "Пулинський ЦОК",
                            StringId = "pl"
                        },
                        new
                        {
                            Id = 21,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 22 },
                            Name = "Черняхівський ЦОК",
                            StringId = "ch"
                        },
                        new
                        {
                            Id = 22,
                            Address = "10003, м. Житомир, майдан Перемоги, 10",
                            CurrentPeriodId = 201901,
                            DistrictIds = new[] { 23 },
                            Name = "Чуднівський ЦОК",
                            StringId = "cd"
                        });
                });

            modelBuilder.Entity("Erc.Households.Domain.DistributionSystemOperator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id")
                        .HasName("pk_distribution_system_operators");

                    b.ToTable("distribution_system_operators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "АТ «Житомиробленерго»"
                        },
                        new
                        {
                            Id = 2,
                            Name = "АТ «Укрзалізниця»"
                        });
                });

            modelBuilder.Entity("Erc.Households.Domain.Exemptions.ExemptionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Coeff")
                        .HasColumnName("coeff")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnName("effective_date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnName("end_date")
                        .HasColumnType("date");

                    b.Property<bool?>("HasLimit")
                        .HasColumnName("has_limit")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_exemption_categories");

                    b.ToTable("exemption_categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Coeff = 100.0m,
                            EffectiveDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Почесні громадяни міста"
                        },
                        new
                        {
                            Id = 2,
                            Coeff = 50.0m,
                            EffectiveDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasLimit = true,
                            Name = "Iнвалiди 1 групи по зору або з ураженням ОРА"
                        },
                        new
                        {
                            Id = 3,
                            Coeff = 50.0m,
                            EffectiveDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasLimit = true,
                            Name = "Iнвалiди 2 групи по зору або з ураженням ОРА"
                        },
                        new
                        {
                            Id = 4,
                            Coeff = 100.0m,
                            EffectiveDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasLimit = true,
                            Name = "Учасник бойових дій та членів родин загиблих в АТО (ООС)"
                        });
                });

            modelBuilder.Entity("Erc.Households.Domain.Payments.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AccountingPointId")
                        .HasColumnName("accounting_point_id")
                        .HasColumnType("integer");

                    b.Property<string>("AccountingPointName")
                        .HasColumnName("accounting_point_name")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnName("amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("BatchId")
                        .HasColumnName("batch_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnterDate")
                        .HasColumnName("enter_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("PayDate")
                        .HasColumnName("pay_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PayerInfo")
                        .HasColumnName("payer_info")
                        .HasColumnType("text");

                    b.Property<int>("PeriodId")
                        .HasColumnName("period_id")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnName("status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnName("type")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("AccountingPointId")
                        .HasName("ix_payments_accounting_point_id");

                    b.HasIndex("BatchId")
                        .HasName("ix_payments_batch_id");

                    b.HasIndex("PeriodId")
                        .HasName("ix_payments_period_id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("Erc.Households.Domain.Payments.PaymentChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DateFieldName")
                        .HasColumnName("date_field_name")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("citext");

                    b.Property<int>("PaymentsType")
                        .HasColumnName("payments_type")
                        .HasColumnType("integer");

                    b.Property<string>("PersonFieldName")
                        .HasColumnName("person_field_name")
                        .HasColumnType("text");

                    b.Property<string>("RecordpointFieldName")
                        .HasColumnName("recordpoint_field_name")
                        .HasColumnType("text");

                    b.Property<string>("SumFieldName")
                        .HasColumnName("sum_field_name")
                        .HasColumnType("text");

                    b.Property<string>("TextDateFormat")
                        .HasColumnName("text_date_format")
                        .HasColumnType("text");

                    b.Property<int>("TotalRecord")
                        .HasColumnName("total_record")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_payment_channels");

                    b.ToTable("payment_channels");
                });

            modelBuilder.Entity("Erc.Households.Domain.Payments.PaymentsBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BranchOfficeId")
                        .HasColumnName("branch_office_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IncomingDate")
                        .HasColumnName("incoming_date")
                        .HasColumnType("date");

                    b.Property<bool>("IsClosed")
                        .HasColumnName("is_closed")
                        .HasColumnType("boolean");

                    b.Property<int>("PaymentChannelId")
                        .HasColumnName("payment_channel_id")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_payment_batches");

                    b.HasIndex("BranchOfficeId")
                        .HasName("ix_payment_batches_branch_office_id");

                    b.HasIndex("PaymentChannelId")
                        .HasName("ix_payment_batches_payment_channel_id");

                    b.ToTable("payment_batches");
                });

            modelBuilder.Entity("Erc.Households.Domain.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AddressId")
                        .HasColumnName("address_id")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("first_name")
                        .HasColumnType("citext")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("IdCardExpDate")
                        .HasColumnName("id_card_exp_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("IdCardIssuanceDate")
                        .HasColumnName("id_card_issuance_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IdCardIssuer")
                        .HasColumnName("id_card_issuer")
                        .HasColumnType("citext");

                    b.Property<string>("IdCardNumber")
                        .IsRequired()
                        .HasColumnName("id_card_number")
                        .HasColumnType("citext")
                        .HasMaxLength(9);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("last_name")
                        .HasColumnType("citext")
                        .HasMaxLength(50);

                    b.Property<string[]>("MobilePhones")
                        .HasColumnName("mobile_phones")
                        .HasColumnType("varchar(15)[]");

                    b.Property<string>("Patronymic")
                        .HasColumnName("patronymic")
                        .HasColumnType("citext")
                        .HasMaxLength(50);

                    b.Property<string>("TaxCode")
                        .HasColumnName("tax_code")
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.HasIndex("AddressId")
                        .HasName("ix_people_address_id");

                    b.HasIndex("IdCardNumber")
                        .IsUnique()
                        .HasName("ix_people_id_card_number");

                    b.HasIndex("TaxCode")
                        .IsUnique()
                        .HasName("ix_people_tax_code");

                    b.ToTable("people");
                });

            modelBuilder.Entity("Erc.Households.Domain.Tariffs.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("citext")
                        .HasMaxLength(200);

                    b.HasKey("Id")
                        .HasName("pk_tariffs");

                    b.ToTable("tariffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Населення (загальний тариф)"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Будинки з електроопалювальними установками"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Багатоквартирні негазифіковані будинки"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Багатодітні, прийомні сім'ї та дитячі будинки сімейного типу"
                        });
                });

            modelBuilder.Entity("Erc.Households.Domain.Tariffs.TariffRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ConsumptionLimit")
                        .HasColumnName("consumption_limit")
                        .HasColumnType("integer");

                    b.Property<int?>("HeatingConsumptionLimit")
                        .HasColumnName("heating_consumption_limit")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HeatingEndDay")
                        .HasColumnName("heating_end_day")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("HeatingStartDay")
                        .HasColumnName("heating_start_day")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("start_date")
                        .HasColumnType("date");

                    b.Property<int>("TariffId")
                        .HasColumnName("tariff_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnName("value")
                        .HasColumnType("decimal(8,5)");

                    b.HasKey("Id")
                        .HasName("pk_tariff_rate");

                    b.HasIndex("TariffId")
                        .HasName("ix_tariff_rate_tariff_id");

                    b.ToTable("tariff_rates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsumptionLimit = 100,
                            StartDate = new DateTime(2017, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TariffId = 1,
                            Value = 0.9m
                        },
                        new
                        {
                            Id = 2,
                            StartDate = new DateTime(2017, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TariffId = 1,
                            Value = 1.68m
                        },
                        new
                        {
                            Id = 3,
                            ConsumptionLimit = 100,
                            HeatingConsumptionLimit = 3000,
                            HeatingEndDay = new DateTime(2020, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HeatingStartDay = new DateTime(2019, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2017, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TariffId = 2,
                            Value = 0.90m
                        },
                        new
                        {
                            Id = 4,
                            StartDate = new DateTime(2017, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TariffId = 2,
                            Value = 1.68m
                        },
                        new
                        {
                            Id = 5,
                            ConsumptionLimit = 100,
                            HeatingConsumptionLimit = 3000,
                            HeatingEndDay = new DateTime(2020, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HeatingStartDay = new DateTime(2019, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2017, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TariffId = 3,
                            Value = 0.90m
                        },
                        new
                        {
                            Id = 6,
                            StartDate = new DateTime(2017, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TariffId = 3,
                            Value = 1.68m
                        },
                        new
                        {
                            Id = 7,
                            StartDate = new DateTime(2017, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TariffId = 4,
                            Value = 0.90m
                        });
                });

            modelBuilder.Entity("Erc.Households.Domain.AccountingPoints.AccountingPoint", b =>
                {
                    b.HasOne("Erc.Households.Domain.Addresses.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .HasConstraintName("fk_accounting_points_addresses_address_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erc.Households.Domain.BranchOffice", "BranchOffice")
                        .WithMany()
                        .HasForeignKey("BranchOfficeId")
                        .HasConstraintName("fk_accounting_points_branch_offices_branch_office_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erc.Households.Domain.AccountingPoints.BuildingType", "BuildingType")
                        .WithMany()
                        .HasForeignKey("BuildingTypeId")
                        .HasConstraintName("fk_accounting_points_building_types_building_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erc.Households.Domain.DistributionSystemOperator", "DistributionSystemOperator")
                        .WithMany()
                        .HasForeignKey("DistributionSystemOperatorId")
                        .HasConstraintName("fk_accounting_points_distribution_system_operators_distributio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erc.Households.Domain.Person", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("fk_accounting_points_people_owner_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erc.Households.Domain.AccountingPoints.UsageCategory", "UsageCategory")
                        .WithMany()
                        .HasForeignKey("UsageCategoryId")
                        .HasConstraintName("fk_accounting_points_usage_categories_usage_category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Erc.Households.Domain.AccountingPoints.AccountingPointExemption", "Exemptions", b1 =>
                        {
                            b1.Property<int>("AccountingPointId")
                                .HasColumnName("accounting_point_id")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("id")
                                .HasColumnType("integer")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<string>("Certificate")
                                .HasColumnName("certificate")
                                .HasColumnType("text");

                            b1.Property<DateTime>("EffectiveDate")
                                .HasColumnName("effective_date")
                                .HasColumnType("date");

                            b1.Property<DateTime?>("EndDate")
                                .HasColumnName("end_date")
                                .HasColumnType("date");

                            b1.Property<int>("ExemptionCategoryId")
                                .HasColumnName("exemption_category_id")
                                .HasColumnType("integer");

                            b1.Property<bool>("HasLimit")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("has_limit")
                                .HasColumnType("boolean")
                                .HasDefaultValue(true);

                            b1.Property<string>("Note")
                                .HasColumnName("note")
                                .HasColumnType("text");

                            b1.Property<int>("PersonId")
                                .HasColumnName("person_id")
                                .HasColumnType("integer");

                            b1.Property<int>("PersonsNumber")
                                .HasColumnName("persons_number")
                                .HasColumnType("integer");

                            b1.HasKey("AccountingPointId", "Id")
                                .HasName("pk_accounting_point_exemption");

                            b1.HasIndex("ExemptionCategoryId")
                                .HasName("ix_accounting_point_exemption_exemption_category_id");

                            b1.HasIndex("PersonId")
                                .HasName("ix_accounting_point_exemption_person_id");

                            b1.ToTable("accounting_point_exemptions");

                            b1.WithOwner()
                                .HasForeignKey("AccountingPointId")
                                .HasConstraintName("fk_accounting_point_exemption_accounting_points_accounting_poin");

                            b1.HasOne("Erc.Households.Domain.Exemptions.ExemptionCategory", "Category")
                                .WithMany()
                                .HasForeignKey("ExemptionCategoryId")
                                .HasConstraintName("fk_accounting_point_exemption_exemption_categories_exemption_c")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.HasOne("Erc.Households.Domain.Person", "Person")
                                .WithMany()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_accounting_point_exemption_people_person_id")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    b.OwnsMany("Erc.Households.Domain.AccountingPoints.AccountingPointTariff", "TariffsHistory", b1 =>
                        {
                            b1.Property<int>("AccountingPointId")
                                .HasColumnName("accounting_point_id")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("id")
                                .HasColumnType("integer")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<IReadOnlyCollection<ObjectLog>>("Logs")
                                .HasColumnName("logs")
                                .HasColumnType("jsonb");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnName("start_date")
                                .HasColumnType("date");

                            b1.Property<int>("TariffId")
                                .HasColumnName("tariff_id")
                                .HasColumnType("integer");

                            b1.HasKey("AccountingPointId", "Id")
                                .HasName("pk_accounting_point_tariff");

                            b1.HasIndex("TariffId")
                                .HasName("ix_accounting_point_tariff_tariff_id");

                            b1.ToTable("accounting_point_tariffs");

                            b1.WithOwner()
                                .HasForeignKey("AccountingPointId")
                                .HasConstraintName("fk_accounting_point_tariff_accounting_points_accounting_point_id");

                            b1.HasOne("Erc.Households.Domain.Tariffs.Tariff", "Tariff")
                                .WithMany()
                                .HasForeignKey("TariffId")
                                .HasConstraintName("fk_accounting_point_tariff_tariffs_tariff_id")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });

                    b.OwnsMany("Erc.Households.Domain.AccountingPoints.Contract", "ContractsHistory", b1 =>
                        {
                            b1.Property<int>("AccountingPointId")
                                .HasColumnName("accounting_point_id")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("id")
                                .HasColumnType("integer")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<int>("CustomerId")
                                .HasColumnName("customer_id")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("EndDate")
                                .HasColumnName("end_date")
                                .HasColumnType("date");

                            b1.Property<IReadOnlyCollection<ObjectLog>>("Logs")
                                .HasColumnName("logs")
                                .HasColumnType("jsonb");

                            b1.Property<bool>("SendPaperBill")
                                .HasColumnName("send_paper_bill")
                                .HasColumnType("boolean");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnName("start_date")
                                .HasColumnType("date");

                            b1.HasKey("AccountingPointId", "Id")
                                .HasName("pk_contract");

                            b1.HasIndex("CustomerId")
                                .HasName("ix_contract_customer_id");

                            b1.ToTable("contracts");

                            b1.WithOwner()
                                .HasForeignKey("AccountingPointId")
                                .HasConstraintName("fk_contract_accounting_points_accounting_point_id");

                            b1.HasOne("Erc.Households.Domain.Person", "Customer")
                                .WithMany()
                                .HasForeignKey("CustomerId")
                                .HasConstraintName("fk_contract_people_customer_id")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });
                });

            modelBuilder.Entity("Erc.Households.Domain.Addresses.Address", b =>
                {
                    b.HasOne("Erc.Households.Domain.Addresses.Street", "Street")
                        .WithMany()
                        .HasForeignKey("StreetId")
                        .HasConstraintName("fk_addresses_streets_street_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Erc.Households.Domain.Addresses.City", b =>
                {
                    b.HasOne("Erc.Households.Domain.Addresses.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .HasConstraintName("fk_cities_districts_district_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Erc.Households.Domain.Addresses.District", b =>
                {
                    b.HasOne("Erc.Households.Domain.Addresses.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .HasConstraintName("fk_districts_regions_region_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Erc.Households.Domain.Addresses.Street", b =>
                {
                    b.HasOne("Erc.Households.Domain.Addresses.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .HasConstraintName("fk_streets_cities_city_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Erc.Households.Domain.Billing.Invoice", b =>
                {
                    b.HasOne("Erc.Households.Domain.AccountingPoints.AccountingPoint", "AccountingPoint")
                        .WithMany("Invoices")
                        .HasForeignKey("AccountingPointId")
                        .HasConstraintName("fk_invoices_accounting_points_accounting_point_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erc.Households.Domain.Billing.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .HasConstraintName("fk_invoices_period_period_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erc.Households.Domain.Tariffs.Tariff", "Tariff")
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .HasConstraintName("fk_invoices_tariffs_tariff_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Erc.Households.Domain.Billing.InvoicePaymentItem", b =>
                {
                    b.HasOne("Erc.Households.Domain.Billing.Invoice", "Invoice")
                        .WithMany("InvoicePaymentItems")
                        .HasForeignKey("InvoiceId")
                        .HasConstraintName("fk_invoice_payment_item_invoices_invoice_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erc.Households.Domain.Payments.Payment", "Payment")
                        .WithMany("InvoicePaymentItems")
                        .HasForeignKey("PaymentId")
                        .HasConstraintName("fk_invoice_payment_item_payments_payment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Erc.Households.Domain.BranchOffice", b =>
                {
                    b.HasOne("Erc.Households.Domain.Billing.Period", "CurrentPeriod")
                        .WithMany()
                        .HasForeignKey("CurrentPeriodId")
                        .HasConstraintName("fk_branch_offices_period_current_period_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Erc.Households.Domain.Payments.Payment", b =>
                {
                    b.HasOne("Erc.Households.Domain.AccountingPoints.AccountingPoint", "AccountingPoint")
                        .WithMany("Payments")
                        .HasForeignKey("AccountingPointId")
                        .HasConstraintName("fk_payments_accounting_points_accounting_point_id");

                    b.HasOne("Erc.Households.Domain.Payments.PaymentsBatch", "Batch")
                        .WithMany("Payments")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("fk_payments_payment_batches_batch_id");

                    b.HasOne("Erc.Households.Domain.Billing.Period", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .HasConstraintName("fk_payments_period_period_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Erc.Households.Domain.Payments.PaymentsBatch", b =>
                {
                    b.HasOne("Erc.Households.Domain.BranchOffice", "BranchOffice")
                        .WithMany()
                        .HasForeignKey("BranchOfficeId")
                        .HasConstraintName("fk_payment_batches_branch_offices_branch_office_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erc.Households.Domain.Payments.PaymentChannel", "PaymentChannel")
                        .WithMany()
                        .HasForeignKey("PaymentChannelId")
                        .HasConstraintName("fk_payment_batches_payment_channels_payment_channel_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Erc.Households.Domain.Person", b =>
                {
                    b.HasOne("Erc.Households.Domain.Addresses.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .HasConstraintName("fk_people_addresses_address_id");
                });

            modelBuilder.Entity("Erc.Households.Domain.Tariffs.TariffRate", b =>
                {
                    b.HasOne("Erc.Households.Domain.Tariffs.Tariff", null)
                        .WithMany("Rates")
                        .HasForeignKey("TariffId")
                        .HasConstraintName("fk_tariff_rate_tariffs_tariff_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
